version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: sentineledr-db
    environment:
      POSTGRES_USER: sentineledr
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: sentineledr
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: sentineledr-redis
    ports:
      - "6379:6379"